### ISSUE TITLE
Starting point is always the first point in the path

### ISSUE THREAD

**Issue by MasterEric** [lovasoa/salesman.js#5]
https://github.com/lovasoa/salesman.js/blob/14ac3100aea0a13fc8d985e536cd1a0635483ae2/salesman.js#L71

Currently the first point in the path is never moved. This should be configurable.

**Comment by lovasoa** [comment]
I am not sure I understand the goal here. We are working on a closed path, so there is no "first point". By convention, the code works with an array that starts with the first point in the input points array. But since the path is closed, the resulting path can be executed from any point without changing the total length.

**Comment by MasterEric** [comment]
Aaah, I see.

I guess this inquiry only makes sense in the context of an open path (which is the use case I came to this repository for).

After more research, this may be out of the scope of a Salesman library as it falls under the concept of a 'Hamiltonian' path.
